/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVerifyIdRouteImport } from './routes/api/verify-id'
import { Route as ApiPublicResetPasswordRouteImport } from './routes/api/public/reset-password'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyIdRoute = ApiVerifyIdRouteImport.update({
  id: '/api/verify-id',
  path: '/api/verify-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResetPasswordRoute = ApiPublicResetPasswordRouteImport.update({
  id: '/api/public/reset-password',
  path: '/api/public/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/verify-id': typeof ApiVerifyIdRoute
  '/api/public/reset-password': typeof ApiPublicResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/verify-id': typeof ApiVerifyIdRoute
  '/api/public/reset-password': typeof ApiPublicResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/verify-id': typeof ApiVerifyIdRoute
  '/api/public/reset-password': typeof ApiPublicResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/api/verify-id' | '/api/public/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/api/verify-id' | '/api/public/reset-password'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/verify-id'
    | '/api/public/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiVerifyIdRoute: typeof ApiVerifyIdRoute
  ApiPublicResetPasswordRoute: typeof ApiPublicResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-id': {
      id: '/api/verify-id'
      path: '/api/verify-id'
      fullPath: '/api/verify-id'
      preLoaderRoute: typeof ApiVerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reset-password': {
      id: '/api/public/reset-password'
      path: '/api/public/reset-password'
      fullPath: '/api/public/reset-password'
      preLoaderRoute: typeof ApiPublicResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiVerifyIdRoute: ApiVerifyIdRoute,
  ApiPublicResetPasswordRoute: ApiPublicResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
