REVOKE EXECUTE ON FUNCTION public.accept_roommate_connect(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.send_roommate_connect(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.mark_all_notifications_read() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.respond_viewing_request(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.set_security_question(text, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.set_initial_role(public.app_role) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_roommate_sender_public(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_landlord_public(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.approve_agency(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.decline_agency(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.send_announcement(text, text, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.match_roommate_requests(uuid, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.list_pending_agencies() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.verify_security_answer(text, text) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.accept_roommate_connect(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.send_roommate_connect(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_all_notifications_read() TO authenticated;
GRANT EXECUTE ON FUNCTION public.respond_viewing_request(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_security_question(text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_initial_role(public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_roommate_sender_public(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_landlord_public(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_agency(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.decline_agency(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.send_announcement(text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.match_roommate_requests(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_pending_agencies() TO authenticated;